# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-03 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_user_login_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='pid',
            field=models.IntegerField(default=0),
        ),
    ]
