# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_process_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
